apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-operator
  namespace: cicd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  source:
    path: .
    repoURL: https://charts.jetstack.io
    targetRevision: v1.18.2
    chart: cert-manager
    helm:
      parameters:
        - name: installCRDs
          value: 'true'
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true