apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crds
  namespace: cicd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  source:
    path: .
    repoURL: http://gitea-http-lb.cicd.svc.cluster.local:8081/devops/crds.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
