apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-operator
  namespace: cicd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    path: .
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: v5.18.0
    chart: grafana-operator
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true