apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: cicd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    path: .
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 1.23.2
    chart: tempo
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
