apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-operator
  namespace: cicd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  source:
    path: .
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    targetRevision: 0.90.4
    chart: opentelemetry-operator
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true