apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: grpc-instrumentation
  namespace: dev
spec:
  exporter:
    endpoint: http://traces-collector:4318
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"