apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitea
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: gitea
    app.kubernetes.io/version: 1.24.2
    helm.sh/chart: gitea-12.1.1
    version: 1.24.2
  name: gitea-http-lb
  namespace: cicd
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 3000
  selector:
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/name: gitea
  type: LoadBalancer
