apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    argocd.argoproj.io/instance: dev
    argocd.argoproj.io/managed-by: cicd
spec: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    argocd.argoproj.io/instance: cert-manager
    argocd.argoproj.io/managed-by: cicd
spec: {}
